// <auto-generated />
using System;
using Hospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20230611171105_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87125863-fd72-4e2b-ab90-69f43e8e5928"),
                            Name = "Jessie",
                            PerformanceRate = 65,
                            Salary = 27064m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("7f142e14-2fb1-4e88-bf7c-29c9d33faf60"),
                            Name = "Judy",
                            PerformanceRate = 32,
                            Salary = 18711m,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("b6132b34-f470-49cf-92c4-463cbc3f54e0"),
                            Name = "Naomi",
                            PerformanceRate = 27,
                            Salary = 32145m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("db630dc7-9e11-44a4-9c7b-3be040c8dfe1"),
                            Name = "Joann",
                            PerformanceRate = 72,
                            Salary = 9232m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("0028f547-7246-422b-a461-4e44e3020f17"),
                            Name = "Judy",
                            PerformanceRate = 19,
                            Salary = 48498m,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("da1a37f1-8e7b-4864-b83c-0c1df42c4f80"),
                            Name = "Alyssa",
                            PerformanceRate = 79,
                            Salary = 16586m,
                            Specialization = "Gastroenterology"
                        },
                        new
                        {
                            Id = new Guid("5ca86934-de29-42cc-a77f-f57636a6a968"),
                            Name = "Mable",
                            PerformanceRate = 5,
                            Salary = 33706m,
                            Specialization = "Infectious Disease"
                        },
                        new
                        {
                            Id = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Paula",
                            PerformanceRate = 0,
                            Salary = 19094m,
                            Specialization = "Urology"
                        },
                        new
                        {
                            Id = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Rafael",
                            PerformanceRate = 97,
                            Salary = 12266m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("731d1963-a780-4942-ac97-50dc5fd2a8d6"),
                            Name = "Sara",
                            PerformanceRate = 82,
                            Salary = 45041m,
                            Specialization = "Pediatrics"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7846fc85-347f-4c90-9107-90be08bd1c02"),
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = new Guid("1279c557-f58b-450d-8532-d9471f1320fc"),
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = new Guid("dcbaf073-3660-4031-a7c4-24697b183f3a"),
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = new Guid("83adbdea-1fcd-4ae8-9a5a-bbe7fa9e0ba8"),
                            Name = "Depression"
                        },
                        new
                        {
                            Id = new Guid("938c2da0-ae7f-43ee-9b4b-6e5e6fa91500"),
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = new Guid("1539d778-d1a1-4848-bc76-75ec4175a718"),
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = new Guid("e04d760e-b3ee-469b-b0ac-91b1595366b3"),
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6065292f-89be-4285-9c22-69370be9cbd0"),
                            DoctorId = new Guid("da1a37f1-8e7b-4864-b83c-0c1df42c4f80"),
                            Name = "Dana"
                        },
                        new
                        {
                            Id = new Guid("af29b6d9-6a7d-4896-8082-eef07f299e9d"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = new Guid("9849e376-36ee-4b41-84c1-a5ed1d2efe84"),
                            DoctorId = new Guid("731d1963-a780-4942-ac97-50dc5fd2a8d6"),
                            Name = "Damon"
                        },
                        new
                        {
                            Id = new Guid("2d6b1e75-e41a-4702-a0d8-4443e2abdf88"),
                            DoctorId = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Miriam"
                        },
                        new
                        {
                            Id = new Guid("7e7c5ca2-5bf5-49d1-ad8e-9cc754d1ef54"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Terence"
                        },
                        new
                        {
                            Id = new Guid("a510d03c-0795-436e-845c-edf77756ddfe"),
                            DoctorId = new Guid("7f142e14-2fb1-4e88-bf7c-29c9d33faf60"),
                            Name = "Roosevelt"
                        },
                        new
                        {
                            Id = new Guid("909abbec-1fe0-4cf3-ae94-a1c44b9753bd"),
                            DoctorId = new Guid("731d1963-a780-4942-ac97-50dc5fd2a8d6"),
                            Name = "Eduardo"
                        },
                        new
                        {
                            Id = new Guid("b61a5c34-4266-41b7-a15b-46b38792d66b"),
                            DoctorId = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Wilbert"
                        },
                        new
                        {
                            Id = new Guid("60b22b07-267c-44ba-86de-7c7ff88a2c58"),
                            DoctorId = new Guid("da1a37f1-8e7b-4864-b83c-0c1df42c4f80"),
                            Name = "Tasha"
                        },
                        new
                        {
                            Id = new Guid("1ef012e0-c502-4e3e-bdfc-d92131289e3c"),
                            DoctorId = new Guid("7f142e14-2fb1-4e88-bf7c-29c9d33faf60"),
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("f5024a5e-e9cd-40a9-ac58-8b88ddba76f1"),
                            DoctorId = new Guid("b6132b34-f470-49cf-92c4-463cbc3f54e0"),
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("fbb649c4-ffab-41f0-b9dd-8dd8b5d71573"),
                            DoctorId = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Juan"
                        },
                        new
                        {
                            Id = new Guid("1e51f1e6-b682-4881-b02b-f8fccf706ffe"),
                            DoctorId = new Guid("87125863-fd72-4e2b-ab90-69f43e8e5928"),
                            Name = "Krystal"
                        },
                        new
                        {
                            Id = new Guid("7865b992-2d87-41ea-9241-0ed5a3de51d7"),
                            DoctorId = new Guid("87125863-fd72-4e2b-ab90-69f43e8e5928"),
                            Name = "Erma"
                        },
                        new
                        {
                            Id = new Guid("459974e8-bc5d-4429-bbc6-58c7e3ec9934"),
                            DoctorId = new Guid("5ca86934-de29-42cc-a77f-f57636a6a968"),
                            Name = "Orlando"
                        },
                        new
                        {
                            Id = new Guid("85e492c1-c047-4d5b-93e1-ef99080a9678"),
                            DoctorId = new Guid("da1a37f1-8e7b-4864-b83c-0c1df42c4f80"),
                            Name = "Marvin"
                        },
                        new
                        {
                            Id = new Guid("eb379f4b-8dee-4a19-843c-c51589bb5e40"),
                            DoctorId = new Guid("0028f547-7246-422b-a461-4e44e3020f17"),
                            Name = "Lamar"
                        },
                        new
                        {
                            Id = new Guid("f2c0dea3-ee95-4d30-8f32-9f5c580d21fe"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Joe"
                        },
                        new
                        {
                            Id = new Guid("f07c7d60-d715-4cf9-9c24-778069d38320"),
                            DoctorId = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Wendell"
                        },
                        new
                        {
                            Id = new Guid("b197c712-a24f-4276-b1de-c26d44a7bc50"),
                            DoctorId = new Guid("0028f547-7246-422b-a461-4e44e3020f17"),
                            Name = "Sandra"
                        },
                        new
                        {
                            Id = new Guid("48bd8ac4-3cf7-4a1a-b445-8cd6572ad90b"),
                            DoctorId = new Guid("5ca86934-de29-42cc-a77f-f57636a6a968"),
                            Name = "Stephanie"
                        },
                        new
                        {
                            Id = new Guid("3d0f68c1-3cda-4772-a9fa-39c758fc8905"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Ervin"
                        },
                        new
                        {
                            Id = new Guid("d66579a4-399e-41dd-9d9c-28c2422b7578"),
                            DoctorId = new Guid("0028f547-7246-422b-a461-4e44e3020f17"),
                            Name = "Beth"
                        },
                        new
                        {
                            Id = new Guid("3140e784-e3a7-4f03-acae-ebb22803f6cc"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Gretchen"
                        },
                        new
                        {
                            Id = new Guid("cdfad3fe-d2fe-4300-b332-468573df5459"),
                            DoctorId = new Guid("b6132b34-f470-49cf-92c4-463cbc3f54e0"),
                            Name = "Gwendolyn"
                        },
                        new
                        {
                            Id = new Guid("cc8a7039-769c-4eff-a697-bd7a43f38104"),
                            DoctorId = new Guid("15896574-6ca5-4ff6-8851-1bbb309a226f"),
                            Name = "Jerry"
                        },
                        new
                        {
                            Id = new Guid("fb5b6742-a0a2-4d75-855d-594589c2afdb"),
                            DoctorId = new Guid("5ca86934-de29-42cc-a77f-f57636a6a968"),
                            Name = "Mitchell"
                        },
                        new
                        {
                            Id = new Guid("55866a37-f707-4c9d-8a83-29c0fe06ce16"),
                            DoctorId = new Guid("0abcfd04-e9e8-47d0-a5ac-2e4ea829158a"),
                            Name = "Maggie"
                        },
                        new
                        {
                            Id = new Guid("dacc5574-24dd-41bf-8e70-d6830cd8c59b"),
                            DoctorId = new Guid("db630dc7-9e11-44a4-9c7b-3be040c8dfe1"),
                            Name = "Sandy"
                        },
                        new
                        {
                            Id = new Guid("380aa230-45a1-4435-ac5f-e8378e0f935a"),
                            DoctorId = new Guid("b6132b34-f470-49cf-92c4-463cbc3f54e0"),
                            Name = "Lloyd"
                        });
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.Property<Guid>("IssuesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IssuesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("IssuePatient");
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.HasOne("Hospital.DAL.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.HasOne("Hospital.DAL.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.DAL.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
