// <auto-generated />
using System;
using Hospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76a11fcf-dd4d-4d0e-8404-fbf2c5ec8389"),
                            Name = "Jessie",
                            PerformanceRate = 65,
                            Salary = 27064m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("61a671d3-dfd6-40f0-aabb-929160a6e240"),
                            Name = "Judy",
                            PerformanceRate = 32,
                            Salary = 18711m,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("c2c263ee-e86b-45f6-9410-c6d50285120c"),
                            Name = "Naomi",
                            PerformanceRate = 27,
                            Salary = 32145m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("0e3fc154-d0af-4719-9ee8-a7d12563cced"),
                            Name = "Joann",
                            PerformanceRate = 72,
                            Salary = 9232m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("c9395ccb-e7aa-4add-9d5d-de61a0edd297"),
                            Name = "Judy",
                            PerformanceRate = 19,
                            Salary = 48498m,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("cdeb4840-da71-4c67-94e7-d124fa562d68"),
                            Name = "Alyssa",
                            PerformanceRate = 79,
                            Salary = 16586m,
                            Specialization = "Gastroenterology"
                        },
                        new
                        {
                            Id = new Guid("33c644e0-7553-43db-991d-c450fd64adf8"),
                            Name = "Mable",
                            PerformanceRate = 5,
                            Salary = 33706m,
                            Specialization = "Infectious Disease"
                        },
                        new
                        {
                            Id = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Paula",
                            PerformanceRate = 0,
                            Salary = 19094m,
                            Specialization = "Urology"
                        },
                        new
                        {
                            Id = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Rafael",
                            PerformanceRate = 97,
                            Salary = 12266m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("e73fc86f-0724-4a0c-a8fe-52fd7238932d"),
                            Name = "Sara",
                            PerformanceRate = 82,
                            Salary = 45041m,
                            Specialization = "Pediatrics"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3dd5245c-939d-4054-9fa1-0deeaeda24d6"),
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = new Guid("d40dda5c-e113-4d1d-9387-2b91c47517cc"),
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = new Guid("22512b93-8b8b-4139-8c25-75a0aadd9bea"),
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = new Guid("9320a6e7-0b49-48fe-b141-1fa0c9e6a4f8"),
                            Name = "Depression"
                        },
                        new
                        {
                            Id = new Guid("0c7679e6-3214-425d-8e7f-53abe192a6cc"),
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = new Guid("27dcfe13-9a6a-4b3a-b5c2-b8391d70690b"),
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = new Guid("de566c34-94a0-4756-b546-4e50a1f3dd71"),
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44bee883-c171-4dfa-9293-587db3cbf2c5"),
                            DoctorId = new Guid("cdeb4840-da71-4c67-94e7-d124fa562d68"),
                            Name = "Dana"
                        },
                        new
                        {
                            Id = new Guid("2389f8e0-92da-4ce3-ad5f-1299054c7425"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = new Guid("b5ba4cac-3caf-4b07-82e6-25d314edf40d"),
                            DoctorId = new Guid("e73fc86f-0724-4a0c-a8fe-52fd7238932d"),
                            Name = "Damon"
                        },
                        new
                        {
                            Id = new Guid("d75187c2-d690-4e59-960c-916d02be795c"),
                            DoctorId = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Miriam"
                        },
                        new
                        {
                            Id = new Guid("310f2472-3b29-4114-9bb9-32a4de1a2744"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Terence"
                        },
                        new
                        {
                            Id = new Guid("1bdf9193-a144-4b2c-82db-536e1daeda7e"),
                            DoctorId = new Guid("61a671d3-dfd6-40f0-aabb-929160a6e240"),
                            Name = "Roosevelt"
                        },
                        new
                        {
                            Id = new Guid("6d3697d8-a2be-4d9c-856e-a4db7db592b5"),
                            DoctorId = new Guid("e73fc86f-0724-4a0c-a8fe-52fd7238932d"),
                            Name = "Eduardo"
                        },
                        new
                        {
                            Id = new Guid("fe1d49ec-11c6-498f-9b5d-db1f58273e54"),
                            DoctorId = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Wilbert"
                        },
                        new
                        {
                            Id = new Guid("4d8f41f5-d279-4b93-a3fb-e5e0f882bf92"),
                            DoctorId = new Guid("cdeb4840-da71-4c67-94e7-d124fa562d68"),
                            Name = "Tasha"
                        },
                        new
                        {
                            Id = new Guid("b6c39554-980a-424f-a2db-859e15604ea8"),
                            DoctorId = new Guid("61a671d3-dfd6-40f0-aabb-929160a6e240"),
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("66e4a6ea-4872-4228-86ce-93d4371bf882"),
                            DoctorId = new Guid("c2c263ee-e86b-45f6-9410-c6d50285120c"),
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("82f856c8-69f7-4c53-838c-d1972992f383"),
                            DoctorId = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Juan"
                        },
                        new
                        {
                            Id = new Guid("a9a74c48-3996-4d14-b2a5-e3e210817dea"),
                            DoctorId = new Guid("76a11fcf-dd4d-4d0e-8404-fbf2c5ec8389"),
                            Name = "Krystal"
                        },
                        new
                        {
                            Id = new Guid("7d0c01f6-372f-41ff-96ed-d51bcd9572b5"),
                            DoctorId = new Guid("76a11fcf-dd4d-4d0e-8404-fbf2c5ec8389"),
                            Name = "Erma"
                        },
                        new
                        {
                            Id = new Guid("d1bc83c4-91c7-4de3-9431-af5ff1b77bfa"),
                            DoctorId = new Guid("33c644e0-7553-43db-991d-c450fd64adf8"),
                            Name = "Orlando"
                        },
                        new
                        {
                            Id = new Guid("3441d6d0-72f4-45df-864b-5274933a735c"),
                            DoctorId = new Guid("cdeb4840-da71-4c67-94e7-d124fa562d68"),
                            Name = "Marvin"
                        },
                        new
                        {
                            Id = new Guid("76d12572-28b0-4e6b-a820-76d561cb6348"),
                            DoctorId = new Guid("c9395ccb-e7aa-4add-9d5d-de61a0edd297"),
                            Name = "Lamar"
                        },
                        new
                        {
                            Id = new Guid("6bc1cbb3-0ef1-4af0-b8c1-6e4c47329c6d"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Joe"
                        },
                        new
                        {
                            Id = new Guid("8790fb17-2d32-4a8b-b2f5-8c46d5cfd29b"),
                            DoctorId = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Wendell"
                        },
                        new
                        {
                            Id = new Guid("1307e1b3-262f-4f34-8e6c-84712c0a4a96"),
                            DoctorId = new Guid("c9395ccb-e7aa-4add-9d5d-de61a0edd297"),
                            Name = "Sandra"
                        },
                        new
                        {
                            Id = new Guid("4126b03d-84b2-4fbe-bf5d-28dfeb1e3d00"),
                            DoctorId = new Guid("33c644e0-7553-43db-991d-c450fd64adf8"),
                            Name = "Stephanie"
                        },
                        new
                        {
                            Id = new Guid("41f3e020-8f6a-4272-ad3c-21facf5910db"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Ervin"
                        },
                        new
                        {
                            Id = new Guid("b6c8e7c9-4e7c-44ff-aead-9b2d8fdc9e4c"),
                            DoctorId = new Guid("c9395ccb-e7aa-4add-9d5d-de61a0edd297"),
                            Name = "Beth"
                        },
                        new
                        {
                            Id = new Guid("6cd1da93-9730-4bf9-af3d-ae702cfdbc29"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Gretchen"
                        },
                        new
                        {
                            Id = new Guid("7eaf1561-34ba-4137-a69e-7fd42388bafe"),
                            DoctorId = new Guid("c2c263ee-e86b-45f6-9410-c6d50285120c"),
                            Name = "Gwendolyn"
                        },
                        new
                        {
                            Id = new Guid("c54fd8d1-9557-45af-97dc-4d466103c63c"),
                            DoctorId = new Guid("6f09a669-9484-451c-a3ba-4bbafce5a028"),
                            Name = "Jerry"
                        },
                        new
                        {
                            Id = new Guid("53843957-3860-40ca-b990-07cd9f163aa2"),
                            DoctorId = new Guid("33c644e0-7553-43db-991d-c450fd64adf8"),
                            Name = "Mitchell"
                        },
                        new
                        {
                            Id = new Guid("868998f3-c15b-4399-ab42-9c4adc7ef1cd"),
                            DoctorId = new Guid("19d22233-9758-4e00-8ccd-92311e2ba8d6"),
                            Name = "Maggie"
                        },
                        new
                        {
                            Id = new Guid("3712eb13-7afc-4a52-b7a4-3f67d280d241"),
                            DoctorId = new Guid("0e3fc154-d0af-4719-9ee8-a7d12563cced"),
                            Name = "Sandy"
                        },
                        new
                        {
                            Id = new Guid("16bceabe-d0cb-4089-a7f4-84db80e6c404"),
                            DoctorId = new Guid("c2c263ee-e86b-45f6-9410-c6d50285120c"),
                            Name = "Lloyd"
                        });
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.Property<Guid>("IssuesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IssuesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("IssuePatient");
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.HasOne("Hospital.DAL.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.HasOne("Hospital.DAL.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.DAL.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
